"""Airflow DAG code generator from OrchSpec documents.

Produces valid Airflow 2.x DAG Python source using the TaskFlow API.
"""

from __future__ import annotations

import textwrap
from typing import Any

from orchspec_validator.adapters.models import ProjectionResult

# ---------------------------------------------------------------------------
# Executor → Airflow operator mapping
# ---------------------------------------------------------------------------

_EXECUTOR_IMPORTS: dict[str, str] = {
    "python_script": "from airflow.decorators import task",
    "http_request": "from airflow.providers.http.operators.http import SimpleHttpOperator",
    "sql": "from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator",
    "email": "from airflow.operators.email import EmailOperator",
    "bash": "from airflow.operators.bash import BashOperator",
    "container": "from airflow.providers.docker.operators.docker import DockerOperator",
    "custom": "from airflow.operators.python import PythonOperator",
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_airflow_dag(orchspec: dict[str, Any]) -> str:
    """Generate a complete Airflow 2.x DAG Python source file."""
    return _generate_dag(orchspec)


def project_to_airflow(orchspec: dict[str, Any]) -> ProjectionResult:
    """Project an OrchSpec document into an Airflow 2.x DAG Python source."""
    source = _generate_dag(orchspec)
    return ProjectionResult(
        target="airflow",
        artifact_type="airflow_dag_python",
        content={
            "source": source,
            "dag_id": orchspec.get("pipeline_id", "orchspec_pipeline"),
            "format": "python",
        },
    )


# ---------------------------------------------------------------------------
# DAG generator
# ---------------------------------------------------------------------------

def _generate_dag(orchspec: dict[str, Any]) -> str:
    pipeline_id = orchspec.get("pipeline_id", "orchspec_pipeline")
    description = orchspec.get("description", "")
    metadata = orchspec.get("metadata") or {}
    components = orchspec.get("components") or []
    flow = orchspec.get("flow") or {}
    edges = flow.get("edges", [])
    schedule_cfg = orchspec.get("schedule") or {}

    dag_id = _py_ident(pipeline_id)
    owner = metadata.get("owner", "unknown")
    tags = metadata.get("tags", ["orchspec"])

    executor_types = set()
    for comp in components:
        t = (comp.get("executor") or {}).get("type", "custom")
        executor_types.add(t)

    body: list[str] = []
    _emit_imports(body, executor_types, schedule_cfg)
    body.append("")
    _emit_dag_decorator(body, dag_id, schedule_cfg, owner, tags, description)
    body.append(f"def {dag_id}():")
    body.append(f'    """{_escape(description)}"""')

    if not components:
        body.append("    pass")
    else:
        comp_vars: dict[str, str] = {}  # original_id → python variable name
        comp_is_taskflow: dict[str, bool] = {}  # var → True if @task decorated
        for comp in components:
            cid = comp.get("id", "task")
            var = _py_ident(cid)
            exec_type = (comp.get("executor") or {}).get("type", "custom")
            comp_vars[cid] = var
            comp_is_taskflow[var] = (exec_type == "python_script")
            _emit_component(body, var, comp)

        if edges:
            body.append("")
            _emit_dependencies(body, edges, comp_vars, comp_is_taskflow)

    body.append("")
    body.append(f"{dag_id}()")
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------
# Emit helpers — each appends indented lines to `out`
# ---------------------------------------------------------------------------

def _emit_imports(out: list[str], executor_types: set[str], schedule_cfg: dict) -> None:
    out.append("# Generated by OrchSpec → Airflow adapter")
    out.append("from airflow.decorators import dag")
    seen = {"from airflow.decorators import dag"}

    has_taskflow = "python_script" in executor_types
    if has_taskflow:
        line = "from airflow.decorators import task"
        out.append(line)
        seen.add(line)

    for exec_type in sorted(executor_types):
        if exec_type == "python_script":
            continue
        line = _EXECUTOR_IMPORTS.get(exec_type)
        if line and line not in seen:
            out.append(line)
            seen.add(line)

    if schedule_cfg.get("enabled"):
        out.append("from datetime import datetime")
    out.append("from datetime import timedelta")


def _emit_dag_decorator(
    out: list[str], dag_id: str, schedule_cfg: dict,
    owner: str, tags: list, description: str,
) -> None:
    schedule = schedule_cfg.get("cron") if schedule_cfg.get("enabled") else None
    catchup = schedule_cfg.get("catchup", False)
    start_date = schedule_cfg.get("start_date")

    out.append("")
    out.append("@dag(")
    out.append(f'    dag_id="{dag_id}",')
    if description:
        out.append(f'    description="{_escape(description)}",')
    out.append(f'    schedule={_py_str(schedule)},')
    if start_date:
        out.append(f'    start_date=datetime.fromisoformat("{start_date}"),')
    else:
        out.append("    start_date=datetime(2024, 1, 1),")
    out.append(f"    catchup={_py_bool(catchup)},")
    tags_str = ", ".join(f'"{t}"' for t in tags)
    out.append(f"    tags=[{tags_str}],")
    out.append("    default_args={")
    out.append(f'        "owner": "{owner}",')
    out.append("    },")
    out.append(")")


def _emit_component(out: list[str], var: str, comp: dict) -> None:
    exec_type = (comp.get("executor") or {}).get("type", "custom")
    comp_name = comp.get("name", var)
    comp_desc = comp.get("description", "")
    retry = comp.get("retry") or {}
    timeout = comp.get("timeout")
    params = comp.get("parameters") or {}
    script = comp.get("script") or ""
    executor = comp.get("executor") or {}

    task_opts = _build_task_opts(var, retry, timeout)

    if exec_type == "python_script":
        out.append("")
        out.append(f"    @task(")
        out.append(f"        task_id=\"{var}\",")
        if retry.get("max_attempts"):
            out.append(f"        retries={retry['max_attempts']},")
        if retry.get("delay_seconds"):
            out.append(f"        retry_delay=timedelta(seconds={retry['delay_seconds']}),")
        if timeout:
            sec = _parse_duration_seconds(timeout)
            if sec is not None:
                out.append(f"        execution_timeout=timedelta(seconds={sec}),")
        out.append("    )")
        out.append(f"    def {var}(**context):")
        if comp_desc:
            out.append(f'        """{_escape(comp_desc)}"""')
        if params:
            for k in params:
                out.append(f'        {k} = context.get("params", {{}}).get("{k}")')
        if script:
            for line in script.split("\n"):
                out.append(f"        {line}")
        else:
            out.append(f"        # TODO: implement {comp_name}")
        return

    # Operator-based executors
    op_class = _operator_class(exec_type)
    out.append("")
    out.append(f"    {var} = {op_class}(")
    out.append(f"        task_id=\"{var}\",")
    out.extend(f"        {opt}" for opt in task_opts)
    _emit_executor_specific(out, exec_type, comp)
    out.append("    )")


def _emit_executor_specific(out: list[str], exec_type: str, comp: dict) -> None:
    executor = comp.get("executor") or {}
    params = comp.get("parameters") or {}
    script = comp.get("script") or ""

    if exec_type == "http_request":
        method = executor.get("http_method", "GET")
        out.append(f'        http_conn_id="http_default",')
        out.append(f'        endpoint="",')
        out.append(f'        method="{method}",')
        out.append("        response_check=lambda response: response.status_code == 200,")

    elif exec_type == "sql":
        conn_id = executor.get("sql_connection_id") or "postgres_default"
        sql = _escape(script or "SELECT 1")
        out.append(f'        conn_id="{conn_id}",')
        out.append(f'        sql="{sql}",')

    elif exec_type == "email":
        to = params.get("to", "default@example.com")
        subject = params.get("subject", f"OrchSpec: {comp.get('name', 'task')}")
        out.append(f'        to="{to}",')
        out.append(f'        subject="{_escape(subject)}",')
        out.append(f'        html_content="Task completed.",')

    elif exec_type == "bash":
        cmd = _escape(script or "echo 'Hello from OrchSpec'")
        out.append(f'        bash_command="{cmd}",')

    elif exec_type == "container":
        image = comp.get("image_override") or executor.get("image") or "alpine:latest"
        cmd = script or "echo 'Hello'"
        out.append(f'        image="{image}",')
        out.append(f'        command="{_escape(cmd)}",')
        out.append(f'        auto_remove="force",')

    elif exec_type == "custom":
        out.append(f'        python_callable=lambda **kwargs: print("Custom task: {comp.get("name", "task")}"),')


def _emit_dependencies(
    out: list[str], edges: list[dict[str, Any]],
    comp_vars: dict[str, str], comp_is_taskflow: dict[str, bool],
) -> None:
    # Group by source
    succ: dict[str, list[str]] = {}
    for edge in edges:
        src = edge.get("from", "")
        dst = edge.get("to", "")
        if src not in comp_vars or dst not in comp_vars:
            continue
        succ.setdefault(comp_vars[src], []).append(comp_vars[dst])

    for sv, dvs in succ.items():
        sv_ref = f"{sv}()" if comp_is_taskflow.get(sv) else sv
        dvs_refs = [f"{dv}()" if comp_is_taskflow.get(dv) else dv for dv in dvs]
        if len(dvs_refs) == 1:
            out.append(f"    {sv_ref} >> {dvs_refs[0]}")
        else:
            dsts = ", ".join(dvs_refs)
            out.append(f"    {sv_ref} >> [{dsts}]")


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def _py_ident(raw: str) -> str:
    """Convert an arbitrary string to a safe Python identifier."""
    import re
    s = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw))
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        return "task"
    if s[0].isdigit():
        s = "_" + s
    s = s.lower()
    return s


def _py_str(val: str | None) -> str:
    if val is None:
        return "None"
    return f'"{_escape(val)}"'


def _py_bool(val: bool) -> str:
    return "True" if val else "False"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _operator_class(exec_type: str) -> str:
    mapping = {
        "http_request": "SimpleHttpOperator",
        "sql": "SQLExecuteQueryOperator",
        "email": "EmailOperator",
        "bash": "BashOperator",
        "container": "DockerOperator",
        "custom": "PythonOperator",
    }
    return mapping.get(exec_type, "PythonOperator")


def _parse_duration_seconds(raw: str) -> int | None:
    import re
    m = re.match(r"^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$", str(raw).strip())
    if not m:
        return None
    h = int(m.group(1) or 0)
    mi = int(m.group(2) or 0)
    s = int(m.group(3) or 0)
    if h == 0 and mi == 0 and s == 0:
        return None
    return h * 3600 + mi * 60 + s


def _build_task_opts(var: str, retry: dict, timeout: str | None) -> list[str]:
    opts: list[str] = []
    if retry.get("max_attempts"):
        opts.append(f'retries={retry["max_attempts"]},')
    if retry.get("delay_seconds"):
        opts.append(f"retry_delay=timedelta(seconds={retry['delay_seconds']}),")
    if timeout:
        sec = _parse_duration_seconds(timeout)
        if sec is not None:
            opts.append(f"execution_timeout=timedelta(seconds={sec}),")
    return opts
