"""Argo Workflows YAML generator from OrchSpec documents."""

from __future__ import annotations

from typing import Any

from orchspec_validator.adapters.models import ProjectionResult


def project_to_argo(orchspec: dict[str, Any]) -> ProjectionResult:
    source = _generate_workflow_template(orchspec)
    return ProjectionResult(
        target="argo",
        artifact_type="argo_workflow_template_yaml",
        content={
            "source": source,
            "name": orchspec.get("pipeline_id", "orchspec-pipeline"),
            "format": "yaml",
        },
    )


def generate_argo_workflow(orchspec: dict[str, Any]) -> str:
    return _generate_workflow_template(orchspec)


def _generate_workflow_template(orchspec: dict[str, Any]) -> str:
    pipeline_id = orchspec.get("pipeline_id", "orchspec-pipeline")
    description = orchspec.get("description", "")
    components = orchspec.get("components") or []
    flow = orchspec.get("flow") or {}
    edges = flow.get("edges", [])
    schedule_cfg = orchspec.get("schedule") or {}

    name = _k8s_name(pipeline_id)
    out: list[str] = []

    out.append("# Generated by OrchSpec → Argo Workflows adapter")
    out.append("apiVersion: argoproj.io/v1alpha1")
    out.append("kind: WorkflowTemplate")
    out.append("metadata:")
    out.append(f"  name: {name}")
    out.append(f"  annotations:")
    out.append(f"    description: \"{_escape(description)}\"")
    if schedule_cfg.get("enabled") and schedule_cfg.get("cron"):
        out.append("---")
        out.append("apiVersion: argoproj.io/v1alpha1")
        out.append("kind: CronWorkflow")
        out.append("metadata:")
        out.append(f"  name: {name}-cron")
        out.append("spec:")
        out.append(f"  schedule: \"{schedule_cfg['cron']}\"")
        out.append("  workflowSpec:")
        indent = "    "
    else:
        indent = ""

    out.append(f"{indent}spec:")
    out.append(f"{indent}  entrypoint: main")
    if schedule_cfg.get("enabled"):
        out.append(f"{indent}  timezone: \"{schedule_cfg.get('timezone', 'UTC')}\"")
    out.append(f"{indent}  templates:")

    # DAG template (main entrypoint)
    out.append(f"{indent}  - name: main")
    out.append(f"{indent}    dag:")
    out.append(f"{indent}      tasks:")

    task_names: dict[str, str] = {}
    for comp in components:
        cid = comp.get("id", "task")
        tname = _argo_task_name(cid)
        task_names[cid] = tname

    # Build dependency info
    deps: dict[str, list[str]] = {}
    for edge in edges:
        src = edge.get("from", "")
        dst = edge.get("to", "")
        if src in task_names and dst in task_names:
            deps.setdefault(dst, []).append(src)

    # Emit DAG tasks
    for comp in components:
        cid = comp.get("id", "task")
        tname = task_names[cid]
        dep_list = deps.get(cid, [])
        dep_str = ""
        if dep_list:
            dep_names = [task_names[d] for d in dep_list if d in task_names]
            if dep_names:
                dep_str = f"\n{indent}          dependencies: [{', '.join(dep_names)}]"

        out.append(f"{indent}      - name: {tname}")
        out.append(f"{indent}        template: {tname}-template" + dep_str)

    # Emit individual task templates
    for comp in components:
        cid = comp.get("id", "task")
        tname = task_names[cid]
        exec_type = (comp.get("executor") or {}).get("type", "custom")
        script = comp.get("script") or ""
        comp_name = comp.get("name", cid)
        retry = comp.get("retry") or {}
        timeout = comp.get("timeout")

        out.append(f"{indent}  - name: {tname}-template")

        # Retry strategy
        if retry.get("max_attempts"):
            out.append(f"{indent}    retryStrategy:")
            out.append(f"{indent}      limit: {retry['max_attempts']}")
            if retry.get("delay_seconds"):
                out.append(f"{indent}      retryPolicy: Always")
                out.append(f"{indent}      backoff:")
                out.append(f"{indent}        duration: \"{retry['delay_seconds']}s\"")

        # Timeout
        if timeout:
            out.append(f"{indent}    activeDeadlineSeconds: {_parse_iso_duration(timeout) or 300}")
            out.append(f"{indent}    timeout: \"{timeout}\"")

        # Script/container template
        image = comp.get("image_override") or (comp.get("executor") or {}).get("image") or "python:3.11-slim"

        if exec_type == "python_script":
            source = script or f"print('Running {comp_name}')"
            out.append(f"{indent}    script:")
            out.append(f"{indent}      image: {image}")
            out.append(f"{indent}      command: [python]")
            out.append(f"{indent}      source: |")
            for line in source.split("\n"):
                out.append(f"{indent}        {line}")
        elif exec_type == "bash":
            cmd = script or "echo 'Hello from OrchSpec'"
            out.append(f"{indent}    script:")
            out.append(f"{indent}      image: {image}")
            out.append(f"{indent}      command: [bash]")
            out.append(f"{indent}      source: |")
            for line in cmd.split("\n"):
                out.append(f"{indent}        {line}")
        elif exec_type == "container":
            cmd = script or "echo 'Hello'"
            out.append(f"{indent}    container:")
            out.append(f"{indent}      image: {image}")
            if script:
                out.append(f"{indent}      command: [sh, -c]")
                out.append(f"{indent}      args: [\"{_escape(cmd)}\"]")
        elif exec_type == "http_request":
            out.append(f"{indent}    script:")
            out.append(f"{indent}      image: {image}")
            out.append(f"{indent}      command: [python]")
            out.append(f"{indent}      source: |")
            out.append(f"{indent}        import requests")
            out.append(f"{indent}        # HTTP Request: {comp_name}")
            out.append(f"{indent}        response = requests.get('http://localhost')")
            out.append(f"{indent}        print(response.status_code)")
        else:
            out.append(f"{indent}    script:")
            out.append(f"{indent}      image: {image}")
            out.append(f"{indent}      command: [python]")
            out.append(f"{indent}      source: |")
            out.append(f"{indent}        print('OrchSpec task: {comp_name}')")

    return "\n".join(out) + "\n"


def _k8s_name(raw: str) -> str:
    import re
    s = re.sub(r"[^a-z0-9-]", "-", str(raw).lower())
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "orchspec-pipeline"


def _argo_task_name(raw: str) -> str:
    import re
    s = re.sub(r"[^a-z0-9-]", "-", str(raw).lower())
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "task"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _parse_iso_duration(raw: str) -> int | None:
    import re
    m = re.match(r"^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$", str(raw).strip())
    if not m:
        return None
    h = int(m.group(1) or 0)
    mi = int(m.group(2) or 0)
    s = int(m.group(3) or 0)
    if h == 0 and mi == 0 and s == 0:
        return None
    return h * 3600 + mi * 60 + s
