"""Dagster asset-based code generator from OrchSpec documents."""

from __future__ import annotations

from typing import Any

from orchspec_validator.adapters.models import ProjectionResult


def project_to_dagster(orchspec: dict[str, Any]) -> ProjectionResult:
    source = _generate_definitions(orchspec)
    return ProjectionResult(
        target="dagster",
        artifact_type="dagster_definitions_python",
        content={
            "source": source,
            "job_name": orchspec.get("pipeline_id", "orchspec_pipeline"),
            "format": "python",
        },
    )


def generate_dagster_definitions(orchspec: dict[str, Any]) -> str:
    return _generate_definitions(orchspec)


def _generate_definitions(orchspec: dict[str, Any]) -> str:
    pipeline_id = orchspec.get("pipeline_id", "orchspec_pipeline")
    description = orchspec.get("description", "")
    components = orchspec.get("components") or []
    flow = orchspec.get("flow") or {}
    edges = flow.get("edges", [])
    schedule_cfg = orchspec.get("schedule") or {}

    job_name = _py_ident(pipeline_id)
    out: list[str] = []

    # Imports
    out.append("# Generated by OrchSpec → Dagster adapter")
    out.append("from dagster import (")
    out.append("    asset,")
    out.append("    AssetExecutionContext,")
    out.append("    Definitions,")
    out.append("    define_asset_job,")
    out.append("    RetryPolicy,")
    if schedule_cfg.get("enabled"):
        out.append("    ScheduleDefinition,")
    out.append(")")
    out.append("")

    # Build dependency graph
    deps: dict[str, list[str]] = {}
    for edge in edges:
        src = edge.get("from", "")
        dst = edge.get("to", "")
        if src and dst:
            deps.setdefault(dst, []).append(src)

    # Map component IDs to asset names
    asset_names: dict[str, str] = {}
    assets_ordered: list[str] = []

    for comp in components:
        cid = comp.get("id", "task")
        var = _py_ident(cid)
        asset_names[cid] = var
        assets_ordered.append(var)

        retry = comp.get("retry") or {}
        script = comp.get("script") or ""
        comp_name = comp.get("name", var)
        comp_desc = comp.get("description", "")
        exec_type = (comp.get("executor") or {}).get("type", "custom")

        # Asset decorator with deps
        upstream = deps.get(cid, [])
        deps_parts = []
        if upstream:
            upstream_names = [asset_names[u] for u in upstream if u in asset_names]
            if upstream_names:
                deps_parts.append(f"deps=[{', '.join(upstream_names)}]")

        if retry.get("max_attempts"):
            deps_parts.append(f"retry_policy=RetryPolicy(max_retries={retry['max_attempts']})")

        decorator_args = ", ".join(deps_parts)
        if decorator_args:
            out.append(f"@asset({decorator_args})")
        else:
            out.append("@asset")
        out.append(f"def {var}(context: AssetExecutionContext):")
        if comp_desc:
            out.append(f'    """{_escape(comp_desc)}"""')
        if script:
            for line in script.split("\n"):
                out.append(f"    {line}")
        else:
            out.append(f"    # TODO: implement {comp_name} ({exec_type})")
            out.append(f"    context.log.info(\"Running {comp_name}\")")
        out.append("")

    # Definitions
    asset_list = ", ".join(assets_ordered)
    out.append(f"all_assets = [{asset_list}]")
    out.append("")
    out.append(f'all_jobs = [define_asset_job(name="{job_name}", selection="*")]')
    out.append("")

    schedule_parts = []
    if schedule_cfg.get("enabled") and schedule_cfg.get("cron"):
        out.append("all_schedules = [")
        out.append("    ScheduleDefinition(")
        out.append(f'        job=all_jobs[0],')
        out.append(f'        cron_schedule="{schedule_cfg["cron"]}",')
        out.append("    ),")
        out.append("]")
        schedule_parts.append("schedules=all_schedules")

    out.append("")
    defs_parts = ["assets=all_assets", "jobs=all_jobs"] + schedule_parts
    out.append("defs = Definitions(")
    for part in defs_parts:
        out.append(f"    {part},")
    out.append(")")

    return "\n".join(out) + "\n"


def _py_ident(raw: str) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw))
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        return "task"
    if s[0].isdigit():
        s = "_" + s
    return s.lower()


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')
