"""Prefect 2.x flow code generator from OrchSpec documents."""

from __future__ import annotations

from typing import Any

from orchspec_validator.adapters.models import ProjectionResult


def project_to_prefect(orchspec: dict[str, Any]) -> ProjectionResult:
    source = _generate_flow(orchspec)
    return ProjectionResult(
        target="prefect",
        artifact_type="prefect_flow_python",
        content={
            "source": source,
            "flow_name": orchspec.get("pipeline_id", "orchspec_flow"),
            "format": "python",
        },
    )


def generate_prefect_flow(orchspec: dict[str, Any]) -> str:
    return _generate_flow(orchspec)


def _generate_flow(orchspec: dict[str, Any]) -> str:
    pipeline_id = orchspec.get("pipeline_id", "orchspec_flow")
    description = orchspec.get("description", "")
    components = orchspec.get("components") or []
    flow = orchspec.get("flow") or {}
    edges = flow.get("edges", [])
    schedule_cfg = orchspec.get("schedule") or {}

    flow_name = _py_ident(pipeline_id)
    out: list[str] = []

    # Imports
    out.append("# Generated by OrchSpec → Prefect adapter")
    out.append("from prefect import flow, task")
    out.append("from datetime import timedelta")
    out.append("")

    # Emit tasks (decorated functions)
    task_names: dict[str, str] = {}
    task_is_async: dict[str, bool] = {}
    has_params = False

    for comp in components:
        cid = comp.get("id", "task")
        var = _py_ident(cid)
        task_names[cid] = var
        task_is_async[var] = False
        exec_type = (comp.get("executor") or {}).get("type", "custom")
        retry = comp.get("retry") or {}
        timeout = comp.get("timeout")
        script = comp.get("script") or ""
        comp_name = comp.get("name", var)
        params = comp.get("parameters") or {}

        decorator_parts = []
        if retry.get("max_attempts"):
            decorator_parts.append(f"retries={retry['max_attempts']}")
        if retry.get("delay_seconds"):
            decorator_parts.append(f"retry_delay_seconds={retry['delay_seconds']}")
        if timeout:
            sec = _parse_iso_duration(timeout)
            if sec is not None:
                decorator_parts.append(f"timeout_seconds={sec}")

        decorator = f"@task({', '.join(decorator_parts)})" if decorator_parts else "@task"
        out.append(decorator)
        out.append(f"def {var}():")
        out.append(f'    """{_escape(comp_name)}"""')
        if script:
            for line in script.split("\n"):
                out.append(f"    {line}")
        else:
            out.append(f"    # TODO: implement {comp_name} ({exec_type})")
        out.append("")

    # Flow definition
    schedule_line = ""
    if schedule_cfg.get("enabled") and schedule_cfg.get("cron"):
        schedule_line = f'\n@flow(name="{flow_name}", description="{_escape(description)}", log_prints=True)'
    else:
        schedule_line = f'\n@flow(name="{flow_name}", description="{_escape(description)}", log_prints=True)'

    out.append(schedule_line)
    out.append(f"def {flow_name}():")
    out.append(f'    """{_escape(description)}"""')

    # Prefect 2.x: calling @task directly runs synchronously.
    # Order matters — call tasks in their natural order.
    prev_result = None
    for comp in components:
        cid = comp.get("id", "")
        if cid in task_names:
            var = task_names[cid]
            result_var = f"{var}_result"
            out.append(f"    {result_var} = {var}()")

    if schedule_cfg.get("enabled") and schedule_cfg.get("cron"):
        out.append("")
        out.append("")
        out.append("if __name__ == \"__main__\":")
        out.append(f"    {flow_name}.serve(")
        out.append(f'        name="{flow_name}-deployment",')
        out.append(f'        cron="{schedule_cfg["cron"]}",')
        out.append("    )")
    else:
        out.append("")
        out.append("")
        out.append("if __name__ == \"__main__\":")
        out.append(f"    {flow_name}()")

    return "\n".join(out) + "\n"


def _py_ident(raw: str) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9_]", "_", str(raw))
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        return "task"
    if s[0].isdigit():
        s = "_" + s
    return s.lower()


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _parse_iso_duration(raw: str) -> int | None:
    import re
    m = re.match(r"^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$", str(raw).strip())
    if not m:
        return None
    h = int(m.group(1) or 0)
    mi = int(m.group(2) or 0)
    s = int(m.group(3) or 0)
    if h == 0 and mi == 0 and s == 0:
        return None
    return h * 3600 + mi * 60 + s
